// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmvtztrzzctixmjxibcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttdnR6dHJ6emN0aXhtanhpYmNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MzU1MzUsImV4cCI6MjA3MjUxMTUzNX0.74jbAXCdudMLaFfXMjXhZyZE9NDfLO2HUovo1kczlBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});